### ISSUE TITLE
I2C switching using address pin fails.

### ISSUE THREAD

**Issue by Francis-Simera** [adafruit/Adafruit_CircuitPython_BNO055#110]
I can't seem to enable and disable multiple the IMUs connected to the same bus. It either connects to one and only reads from that one regardless of trying to switch via the address pins.

**Comment by caternuson** [comment]
What addresses does an I2C scan show?
https://learn.adafruit.com/scanning-i2c-addresses/circuitpython

**Comment by Francis-Simera** [comment]
The scan only showed 0x28. However, I soon found out I was using the wrong method to switch the addresses. I now make sure that my GPIO pins are in the right states before I connect the IMUs. Not an elegant solution but its working for now.
