### ISSUE TITLE
calibrated and calibration_status do not seem to be working

### ISSUE THREAD

**Issue by ViennaMike** [adafruit/Adafruit_CircuitPython_BNO055#17]

**Comment by ViennaMike** [comment]
Problem was the calibration status wasn't working. Turns out, it's because the version in Pypi is behind and doesn't have the latest changes that are in gitHub.

**Comment by kattni** [comment]
Sounds like you figured it out. I'll get another release out to update the version on PyPI. Thanks for catching this!
