### ISSUE TITLE
Scaling for gyro looks wrong

### ISSUE THREAD

**Issue by peterhinch** [adafruit/Adafruit_CircuitPython_BNO055#24]
If the gyro units are degrees/s the scaling [here](https://github.com/adafruit/Adafruit_CircuitPython_BNO055/blob/f2f1468d566284b30ad268be23b728c81b4679b6/adafruit_bno055.py#L110) should be 16 not 900 (datasheet section 3.6.4.3 table 3-22).

**Comment by ladyada** [comment]
thanks, wanna submit a PR? that would be great!

**Comment by peterhinch** [comment]
Now done.

**Comment by caternuson** [comment]
Looks like this was fixed by #25. Re-open if not.
