### ISSUE TITLE
Allow for accel config in sensor mode

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_BNO055#32]
This is a carry over issue from the older library.
https://github.com/adafruit/Adafruit_Python_BNO055/pull/14

Access to **ACC_Config** register. See sec 3.5.2 of [datasheet](https://cdn-learn.adafruit.com/assets/assets/000/036/832/original/BST_BNO055_DS000_14.pdf).

**Comment by dherrada** [comment]
#51
