### ISSUE TITLE
update guide

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_BNO055#40]
heya @dherrada @siddacious @kattni if there is a breaking library change please also check the guide to update it!
this is is a good one to train @dherrada on :)

**Comment by siddacious** [comment]
@ladyada yup, I assigned @dherrada a todo on BC last week and it looks like he's finished it

**Comment by ladyada** [comment]
ok who will be QAing it by connecting up hardware and testing?

**Comment by siddacious** [comment]
I will

**Comment by ladyada** [comment]
ganbatte! close this when done :)

**Comment by siddacious** [comment]
One small fix, taken care of.
