### ISSUE TITLE
Add example showing i2c-gpio overlay usage on RPI

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_BNO055#53]
The i2c-gpio overlay provides a software I2C interface which doesn't have the clock stretching issue that the Pi's hardware I2C has. Using the i2c-gpio overlay should be possible via this library:
https://github.com/adafruit/Adafruit_Python_Extended_Bus

**Comment by dherrada** [comment]
I'll take a crack at this
