### ISSUE TITLE
Re-using calibration data

### ISSUE THREAD

**Issue by RicDG** [adafruit/Adafruit_CircuitPython_BNO055#66]
As a newcomer to this great sensor and python, I am getting good data using bno055_simpletest.py. It would be very useful if we had the option to save the self-calibration data for re-use at start-up, where repeated calibration is unecessary or causes delays. My searches on the internet indicate that other BNO055 users have the same issue, but have I have not found any workable paython code.

**Comment by ladyada** [comment]
is there any code for doing so on other platforms?

**Comment by RicDG** [comment]
I found https://github.com/adafruit/Adafruit_BNO055/blob/master/examples/restore_offsets/restore_offsets.ino
I also found a recommended 10 step process summarised by a Bosch community moderator at https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/bno055-related-questions/m-p/16432
I am using the BNO055 with a Pi Zero and Python.

**Comment by ladyada** [comment]
ok thanks, we have no ETA for when that would be added so leaving this open. if someone can submit a PR for it, that would be great!

**Comment by FoamyGuy** [comment]
This was resolved by #119, there is now an example that shows how to do the calibration.
