### ISSUE TITLE
[PLEASE HELP] RuntimeError: UART read error: 7 

### ISSUE THREAD

**Issue by jssaditi** [adafruit/Adafruit_CircuitPython_BNO055#96]
Hello, 

I'm trying to use BNO055 with my RPi 4B (Bullseye OS) in UART mode. I've followed all the steps outlined on the Python & CircuitPython page and enabled UART on the RPi but I keep getting the UART write error 7 when I run the bno055_simpletest.py from the examples. The program runs correctly for a second or two but then crashes. 

Image of error message:
![bno055_error](https://user-images.githubusercontent.com/49169332/156328705-8b9b915e-427a-4d9e-abd9-ccf1544620c0.PNG)

Setup of RPi and BNO055:
![RPi_Wiring](https://user-images.githubusercontent.com/49169332/156330222-05194734-9350-4697-a89f-b1c602085005.jpg)
![BNO055_Wiring](https://user-images.githubusercontent.com/49169332/156330250-34451f43-423f-4377-a9fb-1876bc21dec7.jpg)

Is there any way to solve this issue? 
Thank you in advance!

**Comment by ladyada** [comment]
i would use I2C mode rather than UART first, see if that helps

**Comment by jssaditi** [comment]
Awesome, I'll try that and let you know.

**Comment by jssaditi** [comment]
Hi @ladyada,
What are the I2C intialisations required for creating a sensor object on RPi?
 
I only see this piece of code relating to I2C on the Python and CircuitPython page:
`import board
import busio
import adafruit_bno055
i2c = busio.I2C(board.SCL, board.SDA)
sensor = adafruit_bno055.BNO055_I2C(i2c)`

It looks like this is for a CircuitPython board and not Python board.

**Comment by jssaditi** [comment]
Thank you FoamyGuy!

**Comment by ladyada** [comment]
if you need more help please post to the adafruit forums for tech support!
thanks!

**Comment by jssaditi** [comment]
The BNO055 is working with the RPi in I2C mode now.
Thank you so much!!
